export const kpiData = [
  {
    title: "Total Revenue",
    value: "$128,400",
    delta: "+12%",
    positive: true,
    icon: "DollarSign",
    sub: "vs last month",
  },
  {
    title: "Active Projects",
    value: "12",
    delta: "+2",
    positive: true,
    icon: "FolderKanban",
    sub: "vs last month",
  },
  {
    title: "Open Tasks",
    value: "34",
    delta: "-5",
    positive: false,
    icon: "CheckSquare",
    sub: "vs last month",
  },
  {
    title: "Active Clients",
    value: "8",
    delta: "+1",
    positive: true,
    icon: "Users",
    sub: "vs last month",
  },
];

export const revenueData = [
  { month: "Sep", revenue: 82000 },
  { month: "Oct", revenue: 94000 },
  { month: "Nov", revenue: 88000 },
  { month: "Dec", revenue: 106000 },
  { month: "Jan", revenue: 115000 },
  { month: "Feb", revenue: 128400 },
];

export const projectStatusData = [
  { name: "In Progress", value: 5, color: "#FF4533" },
  { name: "Planning", value: 3, color: "#6366F1" },
  { name: "In Review", value: 2, color: "#F59E0B" },
  { name: "Complete", value: 2, color: "#10B981" },
];

export const projects = [
  {
    id: 1,
    name: "Apex Rebrand Campaign",
    client: "Apex Capital",
    status: "In Progress",
    value: "$24,000",
    dueDate: "Mar 15, 2026",
    progress: 68,
    team: ["RB", "KM", "AL"],
  },
  {
    id: 2,
    name: "NovaTech Social Strategy",
    client: "NovaTech Inc.",
    status: "Planning",
    value: "$12,500",
    dueDate: "Apr 2, 2026",
    progress: 22,
    team: ["SM", "TW"],
  },
  {
    id: 3,
    name: "Horizon SEO Overhaul",
    client: "Horizon Media",
    status: "In Review",
    value: "$8,750",
    dueDate: "Mar 5, 2026",
    progress: 85,
    team: ["RB", "DL"],
  },
  {
    id: 4,
    name: "Pulse Email Automation",
    client: "Pulse Health",
    status: "In Progress",
    value: "$15,200",
    dueDate: "Mar 28, 2026",
    progress: 44,
    team: ["KM", "AL", "SM"],
  },
  {
    id: 5,
    name: "Forge Brand Identity",
    client: "Forge Studios",
    status: "Complete",
    value: "$31,000",
    dueDate: "Feb 20, 2026",
    progress: 100,
    team: ["TW", "RB"],
  },
  {
    id: 6,
    name: "Orbit PPC Campaign",
    client: "Orbit Logistics",
    status: "Planning",
    value: "$9,400",
    dueDate: "Apr 18, 2026",
    progress: 10,
    team: ["DL"],
  },
];

export const tasks = [
  {
    id: 1,
    title: "Write Q1 performance report",
    assignee: "RB",
    status: "To Do",
    priority: "High",
    dueDate: "Mar 1, 2026",
  },
  {
    id: 2,
    title: "Design social media assets for Apex",
    assignee: "KM",
    status: "To Do",
    priority: "Medium",
    dueDate: "Mar 4, 2026",
  },
  {
    id: 3,
    title: "Client call — NovaTech kickoff",
    assignee: "SM",
    status: "In Progress",
    priority: "High",
    dueDate: "Feb 28, 2026",
  },
  {
    id: 4,
    title: "Review Horizon SEO audit",
    assignee: "DL",
    status: "In Progress",
    priority: "Medium",
    dueDate: "Mar 2, 2026",
  },
  {
    id: 5,
    title: "Update Pulse email sequences",
    assignee: "AL",
    status: "In Review",
    priority: "Low",
    dueDate: "Mar 6, 2026",
  },
  {
    id: 6,
    title: "Final sign-off on Forge brand deck",
    assignee: "TW",
    status: "In Review",
    priority: "High",
    dueDate: "Feb 27, 2026",
  },
  {
    id: 7,
    title: "Send contract to Orbit Logistics",
    assignee: "RB",
    status: "Done",
    priority: "Medium",
    dueDate: "Feb 25, 2026",
  },
  {
    id: 8,
    title: "Reconcile February invoices",
    assignee: "SM",
    status: "Done",
    priority: "High",
    dueDate: "Feb 26, 2026",
  },
];

export const crmContacts = [
  {
    id: 1,
    company: "Apex Capital",
    logoInitials: "AC",
    logoColor: "#6366F1",
    contact: "Marcus Chen",
    phone: "+1 (212) 555-0142",
    email: "m.chen@apexcapital.com",
    website: "apexcapital.com",
    status: "Active Client",
    pipelineStage: "Onboarded",
    service: "Brand Strategy",
    tags: [{ label: "NYC FUNNEL", color: "#6366F1" }],
  },
  {
    id: 2,
    company: "NovaTech Inc.",
    logoInitials: "NT",
    logoColor: "#10B981",
    contact: "Sarah Holloway",
    phone: "+1 (415) 555-0198",
    email: "s.holloway@novatech.io",
    website: "novatech.io",
    status: "Onboarding",
    pipelineStage: "Onboarding",
    service: "Social Media",
    tags: [{ label: "SF FUNNEL", color: "#10B981" }],
  },
  {
    id: 3,
    company: "Horizon Media",
    logoInitials: "HM",
    logoColor: "#F59E0B",
    contact: "Derek Okafor",
    phone: "+1 (310) 555-0173",
    email: "derek@horizonmedia.co",
    website: "horizonmedia.co",
    status: "Active Client",
    pipelineStage: "Onboarded",
    service: "SEO & Content",
    tags: [{ label: "LA FUNNEL", color: "#F59E0B" }],
  },
  {
    id: 4,
    company: "Pulse Health",
    logoInitials: "PH",
    logoColor: "#EF4444",
    contact: "Priya Nair",
    phone: "+1 (646) 555-0261",
    email: "priya@pulsehealth.com",
    website: "pulsehealth.com",
    status: "Active Client",
    pipelineStage: "Onboarded",
    service: "Email Automation",
    tags: [{ label: "NYC FUNNEL", color: "#6366F1" }],
  },
  {
    id: 5,
    company: "Meridian Ventures",
    logoInitials: "MV",
    logoColor: "#8B5CF6",
    contact: "James Whitfield",
    phone: "+1 (628) 555-0034",
    email: "jwhitfield@meridian.vc",
    website: "meridian.vc",
    status: "Proposal",
    pipelineStage: "Deal Pending",
    service: "Paid Media",
    tags: [{ label: "DEAL PENDING", color: "#FF8C00" }],
  },
  {
    id: 6,
    company: "Stride Agency",
    logoInitials: "SA",
    logoColor: "#FF4533",
    contact: "Chloe Dupont",
    phone: "+33 1 55 90 1234",
    email: "chloe@strideagency.fr",
    website: "strideagency.fr",
    status: "Lead",
    pipelineStage: "New Lead",
    service: "Brand Strategy",
    tags: [{ label: "EU FUNNEL", color: "#8888AA" }],
  },
  {
    id: 7,
    company: "Forge Studios",
    logoInitials: "FS",
    logoColor: "#FF8C00",
    contact: "Liam Torres",
    phone: "+1 (512) 555-0087",
    email: "liam@forgestudios.co",
    website: "forgestudios.co",
    status: "Lead",
    pipelineStage: "Strategy Call Booked",
    service: "Video Production",
    tags: [{ label: "CALL BOOKED", color: "#6366F1" }, { label: "TX FUNNEL", color: "#F59E0B" }],
  },
  {
    id: 8,
    company: "Orbit Logistics",
    logoInitials: "OL",
    logoColor: "#06B6D4",
    contact: "Dana Kim",
    phone: "+1 (503) 555-0219",
    email: "dana@orbitlogistics.com",
    website: "orbitlogistics.com",
    status: "Lead",
    pipelineStage: "New Lead",
    service: "PPC Campaigns",
    tags: [{ label: "PNW FUNNEL", color: "#8888AA" }],
  },
  {
    id: 9,
    company: "Velo Capital",
    logoInitials: "VC",
    logoColor: "#EC4899",
    contact: "Regan Park",
    phone: "+1 (305) 555-0144",
    email: "regan@velocapital.io",
    website: "velocapital.io",
    status: "Lead",
    pipelineStage: "Call No Show",
    service: "Paid Media",
    tags: [{ label: "NO SHOW", color: "#F59E0B" }],
  },
  {
    id: 10,
    company: "Crestline Co.",
    logoInitials: "CC",
    logoColor: "#14B8A6",
    contact: "Nora Walsh",
    phone: "+1 (720) 555-0362",
    email: "nora@crestline.co",
    website: "crestline.co",
    status: "Lead",
    pipelineStage: "Did Not Close",
    service: "Brand Strategy",
    tags: [{ label: "LOST", color: "#FF4533" }],
  },
  {
    id: 11,
    company: "Bluewave Media",
    logoInitials: "BM",
    logoColor: "#3B82F6",
    contact: "Oscar Reyes",
    phone: "+1 (213) 555-0091",
    email: "oscar@bluewavemedia.com",
    website: "bluewavemedia.com",
    status: "Lead",
    pipelineStage: "Strategy Call Booked",
    service: "Social Media",
    tags: [{ label: "CALL BOOKED", color: "#6366F1" }, { label: "LA FUNNEL", color: "#F59E0B" }],
  },
  {
    id: 12,
    company: "Zenith Works",
    logoInitials: "ZW",
    logoColor: "#A855F7",
    contact: "Isla Grant",
    phone: "+44 20 7946 0012",
    email: "isla@zenithworks.co.uk",
    website: "zenithworks.co.uk",
    status: "Lead",
    pipelineStage: "Deal Pending",
    service: "SEO & Content",
    tags: [{ label: "UK FUNNEL", color: "#8888AA" }],
  },
];

export const pipeline = [
  { stage: "New Lead",              count: 14, value: "$62,400", color: "#8888AA" },
  { stage: "Strategy Call Booked", count: 9,  value: "$88,500", color: "#6366F1" },
  { stage: "Call No Show",         count: 3,  value: "$18,200", color: "#F59E0B" },
  { stage: "Deal Pending",         count: 6,  value: "$104,000", color: "#FF8C00" },
  { stage: "Did Not Close",        count: 4,  value: "$31,600", color: "#FF4533" },
  { stage: "Onboarding",           count: 7,  value: "$138,400", color: "#818CF8" },
  { stage: "Onboarded",            count: 11, value: "$196,800", color: "#10B981" },
];

export const calendarEvents = [
  {
    id: 1,
    title: "NovaTech Kickoff Call",
    date: "Feb 28",
    time: "10:00 AM",
    type: "Call",
  },
  {
    id: 2,
    title: "Apex Campaign Review",
    date: "Mar 3",
    time: "2:30 PM",
    type: "Meeting",
  },
  {
    id: 3,
    title: "Q1 Team Retrospective",
    date: "Mar 7",
    time: "11:00 AM",
    type: "Internal",
  },
  {
    id: 4,
    title: "Pulse Health Strategy Session",
    date: "Mar 10",
    time: "3:00 PM",
    type: "Meeting",
  },
  {
    id: 5,
    title: "Orbit Logistics Discovery",
    date: "Mar 14",
    time: "9:00 AM",
    type: "Call",
  },
];

export const invoices = [
  {
    id: "INV-0041",
    client: "Apex Capital",
    amount: "$8,000",
    status: "Paid",
    date: "Feb 1, 2026",
    due: "Feb 15, 2026",
  },
  {
    id: "INV-0042",
    client: "Pulse Health",
    amount: "$5,100",
    status: "Paid",
    date: "Feb 5, 2026",
    due: "Feb 19, 2026",
  },
  {
    id: "INV-0043",
    client: "Horizon Media",
    amount: "$2,916",
    status: "Pending",
    date: "Feb 15, 2026",
    due: "Mar 1, 2026",
  },
  {
    id: "INV-0044",
    client: "NovaTech Inc.",
    amount: "$4,167",
    status: "Pending",
    date: "Feb 20, 2026",
    due: "Mar 6, 2026",
  },
  {
    id: "INV-0045",
    client: "Meridian Ventures",
    amount: "$3,500",
    status: "Overdue",
    date: "Jan 20, 2026",
    due: "Feb 3, 2026",
  },
];

export const automations = [
  {
    id: 1,
    name: "New Client Welcome Sequence",
    status: "Active",
    trigger: "Client Onboarded",
    sends: 142,
    lastTriggered: "2 hours ago",
    steps: 5,
  },
  {
    id: 2,
    name: "Monthly Reporting Reminder",
    status: "Active",
    trigger: "Monthly (1st)",
    sends: 24,
    lastTriggered: "28 days ago",
    steps: 3,
  },
  {
    id: 3,
    name: "Proposal Follow-up Series",
    status: "Paused",
    trigger: "Proposal Sent",
    sends: 67,
    lastTriggered: "5 days ago",
    steps: 4,
  },
  {
    id: 4,
    name: "Overdue Invoice Nudge",
    status: "Active",
    trigger: "Invoice 7 Days Overdue",
    sends: 18,
    lastTriggered: "3 days ago",
    steps: 2,
  },
  {
    id: 5,
    name: "Q1 Campaign Launch Blast",
    status: "Draft",
    trigger: "Manual",
    sends: 0,
    lastTriggered: "Never",
    steps: 1,
  },
];

export const teamMembers = [
  {
    id: 1,
    name: "Reuben Brunton",
    role: "Creative Director",
    email: "jordan@zipline.agency",
    phone: "+64 21 123 4567",
    initials: "RB",
    color: "#FF4533",
  },
  {
    id: 2,
    name: "Kira Matsuda",
    role: "Brand Strategist",
    email: "kira@zipline.agency",
    phone: "+64 21 234 5678",
    initials: "KM",
    color: "#6366F1",
  },
  {
    id: 3,
    name: "Sam Morales",
    role: "Account Manager",
    email: "sam@zipline.agency",
    phone: "+64 21 345 6789",
    initials: "SM",
    color: "#10B981",
  },
  {
    id: 4,
    name: "Alex Lee",
    role: "Paid Media Lead",
    email: "alex@zipline.agency",
    phone: "+64 21 456 7890",
    initials: "AL",
    color: "#F59E0B",
  },
  {
    id: 5,
    name: "Tyler Walsh",
    role: "SEO Specialist",
    email: "tyler@zipline.agency",
    phone: "+64 21 567 8901",
    initials: "TW",
    color: "#8B5CF6",
  },
  {
    id: 6,
    name: "Dana Lim",
    role: "Content Strategist",
    email: "dana@zipline.agency",
    phone: "+64 21 678 9012",
    initials: "DL",
    color: "#EC4899",
  },
];

export const activityFeed = [
  {
    id: 1,
    actor: "Reuben B.",
    initials: "RB",
    color: "#FF4533",
    action: "uploaded final brand deck for",
    target: "Forge Studios",
    time: "8 min ago",
  },
  {
    id: 2,
    actor: "Kira M.",
    initials: "KM",
    color: "#6366F1",
    action: "marked task complete:",
    target: "Social media asset pack — Apex",
    time: "34 min ago",
  },
  {
    id: 3,
    actor: "Sam M.",
    initials: "SM",
    color: "#10B981",
    action: "added new contact",
    target: "Chloe Dupont @ Stride Agency",
    time: "1 hr ago",
  },
  {
    id: 4,
    actor: "System",
    initials: "ZP",
    color: "#FF4533",
    action: "sent invoice",
    target: "INV-0044 to NovaTech Inc.",
    time: "2 hr ago",
  },
  {
    id: 5,
    actor: "Alex L.",
    initials: "AL",
    color: "#F59E0B",
    action: "moved project to In Review:",
    target: "Pulse Email Automation",
    time: "3 hr ago",
  },
  {
    id: 6,
    actor: "Tyler W.",
    initials: "TW",
    color: "#8B5CF6",
    action: "completed SEO audit for",
    target: "Horizon Media",
    time: "5 hr ago",
  },
  {
    id: 7,
    actor: "Reuben B.",
    initials: "RB",
    color: "#FF4533",
    action: "created new project:",
    target: "Orbit PPC Campaign",
    time: "Yesterday",
  },
  {
    id: 8,
    actor: "Dana L.",
    initials: "DL",
    color: "#EC4899",
    action: "published content calendar for",
    target: "NovaTech Inc.",
    time: "Yesterday",
  },
];

export const myTasks = tasks.filter((t) =>
  ["To Do", "In Progress"].includes(t.status)
).slice(0, 4);
